### ISSUE TITLE
Question about SketchPolicyNode::GetStateFactor

### ISSUE THREAD

**Issue by ujay-zheng** [HPCRL/ics24tvm#1]
I am very confused about the implementation of this function 
https://github.com/HPCRL/ics24tvm/blob/a2e2ec989d73291acb4ee9e5da14c80fd59d2c42/src/auto_scheduler/search_policy/sketch_policy.cc#L488. Before line 552, you do a lot with the copied ret_state through pstate. But then, you don't use pstate at all

**Comment by Lurkrazy** [comment]
Hello, @ujay-zheng, thank you for pointing out this redundant code in `SketchPolicyNode::GetStateFactor`. We sincerely apologize for any inconvenience caused during your codebase reading due to this issue. Removing this redundant code could bring a potential performance improvement by reducing unnecessary memory copies. We appreciate your attention to the details and will work on fixing this issue.

Thanks again for helping us improve the codebase!

**Comment by Lurkrazy** [comment]
To better understand the codebase, I would also recommend checking out the [HPCRL/tvm](https://github.com/HPCRL/tvm). The implementation is well organized and fully based on Python. This approach may provide additional clarity and make it easier to follow the search strategy logic.

**Comment by ujay-zheng** [comment]
@Lurkrazy Thank you for your reply. This new repo has helped me a lot. I will close the current issue now

**Comment by Lurkrazy** [comment]
Just an update, this has been fix in [Commit 0558769](https://github.com/HPCRL/ics24tvm/commit/0558769abbc6bf813ab4e6afc116b1773580f6bd)
